name: Continuous Integration

on:
  push:
  workflow_dispatch:

jobs:
  build-with-gcc:
    runs-on: cpp-gcc
    timeout-minutes: 25
    
    strategy:
      fail-fast: false
      matrix:
        cxx_standard: [11, 14, 17]
        shared_lib: [ON, OFF]
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2

      - name: Configure cmake
        run: cmake -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DIVI_SDK_SHARED_LIB=${{ matrix.shared_lib }} -DBUILD_TESTING=ON ./

      - name: Compile C++ source
        timeout-minutes: 60
        run: cmake --build ./

      - name: Verify library artifact
        if: ${{ matrix.shared_lib == 'OFF' }}
        run: ls -l ivi-sdk-cpp/libivi-sdk-cpp.a

      - name: Verify library artifact
        if: ${{ matrix.shared_lib == 'ON' }}
        run: ls -l ivi-sdk-cpp/libivi-sdk-cpp.so

      - name: Verify other artifacts
        run: |
          ls -l ivi-sdk-example/ivi-sdk-example
          ls -l ivi-sdk-cpp/tests/ivi-sdk-test

      - name: Run tests
        run: ivi-sdk-cpp/tests/ivi-sdk-test

  build-with-clang:
    runs-on: cpp-clang
    timeout-minutes: 25

    strategy:
      fail-fast: false
      matrix:
        cxx_standard: [11, 14, 17]
        shared_lib: [ON, OFF]
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2

      - name: Configure cmake
        run: cmake -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DIVI_SDK_SHARED_LIB=${{ matrix.shared_lib }} -DBUILD_TESTING=ON ./

      - name: Compile C++ source
        timeout-minutes: 60
        run: cmake --build ./

      - name: Verify library artifact
        if: ${{ matrix.shared_lib == 'OFF' }}
        run: ls -l ivi-sdk-cpp/libivi-sdk-cpp.a

      - name: Verify library artifact
        if: ${{ matrix.shared_lib == 'ON' }}
        run: ls -l ivi-sdk-cpp/libivi-sdk-cpp.so

      - name: Verify other artifacts
        run: |
          ls -l ivi-sdk-example/ivi-sdk-example
          ls -l ivi-sdk-cpp/tests/ivi-sdk-test

      - name: Run tests
        run: ivi-sdk-cpp/tests/ivi-sdk-test
