name: Continuous Integration

on:
  push:
  workflow_dispatch:

jobs:
  build-with-gcc:
    runs-on: mono-runner
    timeout-minutes: 25
    container:
      image: ghcr.io/mythicalgames/ivi-sdk-cpp-ubuntu-gcc:v0.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.IVISDKCPP_GITHUBACTION_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        cxx_standard: [11, 14, 17]
      max-parallel: 3

    steps:
      - uses: actions/checkout@v2

      - name: Configure cmake
        run: cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DBUILD_TESTING=ON ./

      - name: Compile C++ source
        timeout-minutes: 60
        run: cmake --build ./

      - name: Verify artifacts
        run: |
          ls -l ivi-sdk-cpp/libivi-sdk-cpp.a
          ls -l ivi-sdk-example/ivi-sdk-example
          ls -l ivi-sdk-cpp/tests/ivi-sdk-test

      - name: Run tests
        run: ivi-sdk-cpp/tests/ivi-sdk-test

  build-with-clang:
    runs-on: mono-runner
    timeout-minutes: 25
    container:
      image: ghcr.io/mythicalgames/ivi-sdk-cpp-ubuntu-clang:v0.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.IVISDKCPP_GITHUBACTION_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        cxx_standard: [11, 14, 17]
      max-parallel: 3

    steps:
      - uses: actions/checkout@v2

      - name: Configure cmake
        run: cmake -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DBUILD_TESTING=ON ./

      - name: Compile C++ source
        timeout-minutes: 60
        run: cmake --build ./

      - name: Verify artifacts
        run: |
          ls -l ivi-sdk-cpp/libivi-sdk-cpp.a
          ls -l ivi-sdk-example/ivi-sdk-example

      - name: Run tests
        run: ivi-sdk-cpp/tests/ivi-sdk-test
